version: 2.0

references:
  commands:
    setup_puppeteer: &setup_puppeteer
      name: Setup puppeteer
      command: |
        chmod +x ./setup_libxcb.sh
        sh ./setup_libxcb.sh
        yarn install

jobs:
  batch-test:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          paths: node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: *setup_puppeteer
      - save_cache:
          paths: node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run:
          name: notify to slack
          command: |
            PAYLOAD=`cat << EOS
            {
              "attachments": [
                {
                  "title": "[TEST] Auto CrowdWorks",
                  "color": "good",
                  "text": "CrowdWorksで新しく仕事を依頼しました"
                }
              ]
            }
            EOS
            `
            curl -X POST --data-urlencode "payload=$PAYLOAD" $SLACK_WEBHOOK_URL

  batch:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          paths: node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: *setup_puppeteer
      - save_cache:
          paths: node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn start
      - run:
          name: notify to slack
          command: |
            PAYLOAD=`cat << EOS
            {
              "attachments": [
                {
                  "title": "Auto CrowdWorks",
                  "color": "good",
                  "text": "CrowdWorksで新しく仕事を依頼しました"
                }
              ]
            }
            EOS
            `
            curl -X POST --data-urlencode "payload=$PAYLOAD" $SLACK_WEBHOOK_URL

workflows:
  version: 2
  test_workflow:
    jobs:
      - batch-test
  batch_workflow:
    triggers:
      - schedule:
          cron: "0 3,6,9,11,12,13,14 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - batch
