version: 2
jobs:
  batch:
    docker:
      - image: circleci/node:7.10
 
    working_directory: ~/repo
 
    steps:
      - checkout
 
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
 
      - run: chmod +x ./setup_libxcb.sh
      - run: sh ./setup_libxcb.sh
      - run: yarn install
 
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn start

workflows:
  version: 2
  normal_workflow:
    jobs:
      - batch
  # nightly_workflow:
  #   triggers:
  #     - schedule:
  #         cron: "0 1 * * *"
  #         filters:
  #           branches:
  #             only:
  #               - master
  #   jobs:
  #     - batch
