version: 2.0

references:
  commands:
    setup_puppeteer: &setup_puppeteer
      name: Setup puppeteer
      command: |
        chmod +x ./setup_libxcb.sh
        sh ./setup_libxcb.sh
        yarn install

jobs:
  auto_forcast:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          paths: node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: *setup_puppeteer
      - save_cache:
          paths: node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn start

  batch:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          paths: node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: *setup_puppeteer
      - save_cache:
          paths: node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn start

workflows:
  version: 2
  ci_workflow:
    jobs:
      - auto_forcast
  # batch_workflow:
  #   triggers:
  #     - schedule:
  #         cron: "0 3,5,7,8,10,11,12,13,14 * * *"
  #         filters:
  #           branches:
  #             only:
  #               - master
  #   jobs:
  #     - batch
