version: 2.0

references:
  commands:
    setup_puppeteer: &setup_puppeteer
      name: Setup puppeteer
      command: |
        chmod +x ./setup_libxcb.sh
        sh ./setup_libxcb.sh
        yarn install

jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          paths: node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Setup puppeteer
          command: |
            if [ -z "$PUPPETEER" ]; then
              chmod +x ./setup_libxcb.sh
              sh ./setup_libxcb.sh
            fi
      - run: yarn install
      - save_cache:
          paths: node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Execute task
          command: |
            if [ -z "$CI_TASK" ]; then
              yarn task
            else
              echo "[ERROR] Undefined $CI_TASK"
              exit 1
            fi

  update_access_token:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          paths: node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: *setup_puppeteer
      - save_cache:
          paths: node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn update_token

workflows:
  version: 2
  task_workflow:
    jobs:
      - build
  batch_workflow:
    triggers:
      - schedule:
          cron: "0 1,3,5,7,9,11,13,15,17,19,21,23 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update_access_token
